name: just_audio_custom
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  
  # just_audio_platform_interface: ^4.5.0
  
  # just_audio_platform_interface:
  #   path: ../just_audio_platform_interface
  synchronized: ^3.2.0
  just_audio_web: ^0.4.15
  # just_audio_web:
  #   path: ../just_audio_web
  audio_session: ">=0.1.24 <0.3.0"
  rxdart: '>=0.26.0 <0.29.0'
  path: ^1.8.0
  path_provider: ^2.0.0
  async: ^2.5.0
  uuid: '>=3.0.1 <5.0.0'
  crypto: ^3.0.0
  meta: ^1.3.0
  just_audio_platform_interface_custom:
    git:
      url: https://github.com/faizin4107/just_audio_platform_interface_custom.git
      ref: main


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.ryanheise.just_audio_custom
        pluginClass: JustAudioPlugin
      ios:
        pluginClass: JustAudioPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: JustAudioPlugin
        sharedDarwinSource: true
      web:
        default_package: just_audio_web

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
